name: PR Commenter
description: A Buildkite plugin which will comment on pull requests
author: "@mcncl"
requirements:
  - go
  - bash
configuration:
  properties:
    message:
      type: string
    secret-name:
      type: string
  required:
    - secret-name
