env:
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  - name: ":golangci-lint: lint"
    command: golangci-lint run --verbose --timeout 3m
    plugins:
      - docker-compose#v5.2.0:
          config: .buildkite/compose.yaml
          run: golangci-lint
          tty: true

  - name: ":go: test"
    commands:
      - go test -cover -v ./...
    plugins:
      -  docker-compose#v5.2.0:
          config: .buildkite/compose.yaml
          run: golangci-lint
          tty: true
          mount-buildkite-agent: true
  - wait: ~

  - label: "Test plugin"
    command: echo "Sweet plugin!"
    plugins:
      - ssh://git@github.com/mcncl/pr-commenter-buildkite-plugin#cc0ff5e:
          secret-name: SUPER_SECRET_PLUGIN
          message: "By George, I think he's done it"
