#!/usr/bin/env bash

set -euo pipefail

case "$(uname -s)" in
    Linux*)     HOST_GOOS=linux;;
    Darwin*)    HOST_GOOS=darwin;;
    CYGWIN*)    HOST_GOOS=windows;;
    MINGW*)     HOST_GOOS=windows;;
    *)          HOST_GOOS="UNKNOWN"
esac

# Determine host architecture
case "$(uname -m)" in
    x86_64*)    HOST_GOARCH=amd64;;
    i686*)      HOST_GOARCH=386;;
    arm64*)     HOST_GOARCH=arm64;;
    arm*)       HOST_GOARCH=arm;;
    *)          HOST_GOARCH="UNKNOWN"
esac

# because the environment hook runs in ./hooks/environment, we
# want to ensure that we are building a directory up

d=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
build_dir="$(dirname "$d")"

echo "~~~ :electric_plug: Building plugin hooks"
echo "Building for ${HOST_GOOS} on ${HOST_GOARCH}"

run_go () {
    if ! command -v go >/dev/null 2>&1; then
        docker run -w /opt -v .:/opt "${BUILDKITE_PLUGIN_PR_COMMENTER_GO_DOCKER_IMAGE:-golang:alpine}" go "$@"
    else
        go "$@"
    fi
}

cd "${build_dir}" && run_go build -o hooks/pre-exit
